### ISSUE TITLE
[iOS, BE] 숙소 검색 Data 형식 관련

### ISSUE THREAD

**Issue by Settpark** [Jiwon-JJW/airbnb#3]
### 숙소 검색에서 iOS -> BE 전달할 데이터 형식

- 관련 이미지
<img width="303" alt="1" src="https://user-images.githubusercontent.com/64049682/118467329-a9d38880-b73e-11eb-9448-cd378685ccc2.png">

- 데이터 형식

~~class searchCondition {
    location: String
    checkInOut: [String(startDate), String(endDate)] //ex ["20210807", "20210810"]
    pay: [Int(minpay), Int(maxpay)] //ex [10,000 ~ 100,000]
    people: Int
}~~ //2021.05.18 **전달하는 데이터 형태 수정**

- 모든 클래스명과 변수명은 iOS에서 임의로 지정한 것이기 때문에 백엔드에서 편하신대로 수정하셔서 주셔도 상관없습니다.
- 의문사항은 언제든 코멘트 달아주세요.

---
2021.05.18 수정사항

- 2021.05.18 수정 된 데이터 형식 (예시)
"/search/average-price?{$price}checkin={$date}&checkout={$date}"

**Comment by Settpark** [comment]
이슈 내용을 정리하다가 의문점이 있어 글을 남깁니다.
금일(05.18) 수정한 아래와 같은 데이터 형식으로 보낼 때
"/search/average-price?{$price}checkin={$date}&checkout={$date}"

1. 순서는 상관 없이 보내도 되는 건가요?
2. 만약 상관이 있다면 저희가 어떤 형태로 보내야 하는 지 본문의 내용 참고하여 예시 작성을 부탁드릴 수 있을까요?

**Comment by Jiwon-JJW** [comment]
순서는 상관 없이 보내주셔도 괜찮습니다! 
다만, 검색 값이 없을 경우, 아예 주소에 포함시키지 않는 방식으로 해주시면 될 것 같습니다!
변수명들은 오전 내로 정해서 말씀 드리겠습니다!

**Comment by Settpark** [comment]
네 알겠습니다. 변수명이 확정되면 이슈 본문에 업데이트 부탁드립니다.

**Comment by Jiwon-JJW** [comment]
숙소 List(GET: /search)
Request
쿼리스트링 값: locationId, checkIn, checkOut, minPrice, maxPrice, adult, children, infant

예시: `/search?locationId=1&checkin=2021-06-04&checkout=2021-07-04&minPrice=10000&maxPrice=1000000&adult=2&children=1`

으로 정해졌습니다!
좀 더 자세한 API같은 경우, Wiki에 등록해두겠습니다!

**Comment by Settpark** [comment]
네 감사합니다. 확인하였습니다.
