### ISSUE TITLE
DB 설계

### ISSUE THREAD

**Issue by sallyjellyy** [Jiwon-JJW/airbnb#9]
- API 설계 토대로 ERD 그리기
  - 구현하면서 계속 수정할 수 있도록
- 테이블 스키마

**Comment by Jiwon-JJW** [comment]
1차 설계
![Uploading 스크린샷 2021-05-18 오후 3.30.27.png…]()

**Comment by Jiwon-JJW** [comment]
1차 설계
![1차 설계](https://user-images.githubusercontent.com/69128652/118602771-0f328280-b7ee-11eb-924f-9db3e5d2fa04.png)

**Comment by kyupid** [comment]
오우..벌써..짱입니다 대단하세요💯

**Comment by sallyjellyy** [comment]
### 수정사항
- property - image 1 대 다 관계 반대로 설정
  - image가 property_id를 외래키로
- property_detail 테이블
  - type 이름변경 -> room_type
  - cleaning_fee -> int로
  - max_occupancy -> int로

**Comment by Jiwon-JJW** [comment]
## 최종 ERD

<img width="860" alt="스크린샷 2021-05-28 오후 2 48 31" src="https://user-images.githubusercontent.com/69128652/119936229-c89a1080-bfc3-11eb-913c-388e86970655.png">
